definitions:
  api.StudentRequest:
    properties:
      Active:
        type: boolean
      Age:
        type: integer
      CPF:
        type: integer
      Email:
        type: string
      Name:
        type: string
    type: object
  schemas.Student:
    type: object
  schemas.StudentResponse:
    properties:
      Active:
        type: boolean
      Age:
        type: integer
      CPF:
        type: integer
      Email:
        type: string
      Name:
        description: DeletedAt time.Time `json:"deletedAt"`
        type: string
      createdAt:
        type: string
      id:
        type: integer
      updatedAt:
        type: string
    type: object
info:
  contact: {}
paths:
  /students:
    get:
      consumes:
      - application/json
      description: Retrieve students details
      parameters:
      - description: Filter by active students
        in: query
        name: active
        type: boolean
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              items:
                $ref: '#/definitions/schemas.StudentResponse'
              type: array
            type: object
        "404":
          description: Not Found
      summary: Get a list of students
      tags:
      - students
    post:
      consumes:
      - application/json
      description: Create a new student
      parameters:
      - description: Dados do estudante
        in: body
        name: student
        required: true
        schema:
          $ref: '#/definitions/api.StudentRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schemas.StudentResponse'
        "400":
          description: Bad Request
      summary: Create student
      tags:
      - students
  /students/{id}:
    delete:
      consumes:
      - application/json
      description: Delete student by ID
      parameters:
      - description: Student ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schemas.StudentResponse'
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Delete student
      tags:
      - students
    get:
      consumes:
      - application/json
      description: Retrieve student details using ID
      parameters:
      - description: Student ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schemas.StudentResponse'
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Get student by ID
      tags:
      - students
    put:
      consumes:
      - application/json
      description: Update student details
      parameters:
      - description: Student ID
        in: path
        name: id
        required: true
        type: integer
      - description: Updated student data
        in: body
        name: student
        required: true
        schema:
          $ref: '#/definitions/schemas.Student'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schemas.StudentResponse'
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Update student
      tags:
      - students
swagger: "2.0"
